AllCops:
  TargetRubyVersion: 2.3

# Metrics
Metrics/ParameterLists:
  CountKeywordArgs: false

# Style cops
Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
